spring:
  # sql.init.mode: always
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${JDBC_DATABASE_USERNAME:myuser}
    password: ${JDBC_DATABASE_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 250
    
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      # ddl-auto: validate
      ddl-auto: update
      # ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.charSet: UTF-8
      # hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  web:
    # Static resources reloading during development
    # resources.static-locations=${project.base-dir}/src/main/resources/static/
    resources.cache.period: 0
  servlet.multipart:
    # max file size - default 1MB
    max-file-size: 10MB
    # max request size - default 10MB
    max-request-size: 25MB
  thymeleaf:
    # prefix: ${project.base-dir}/src/main/resources/templates/
    cache: false
  devtools.livereload.enabled: false
springdoc:
  pathsToMatch: /api/**
logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
  org.hibernate: ERROR
  org.springframework.web: DEBUG
